apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  labels:
    app: ci-base
  name: ci-base
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: ci-base:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: console-jenkins
    git:
      uri: https://github.com/rcangiamila/selenium-servers.git
    type: Git
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: jenkins-2-rhel7:latest
    type: Docker
  triggers:
  - github:
      secret: X3lE4wcLwH8EQTTrmjE1
    type: GitHub
  - generic:
      secret: YCVWpricl61bbstlLN-t
    type: Generic
  - type: ConfigChange
  - imageChange: {}
    type: ImageChange
status:
  lastVersion: 0
