apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  generation: 1
  labels:
    app: ci-base
  name: ci-base
spec:
  replicas: 0
  selector:
    app: ci-base
    deploymentconfig: ci-base
  strategy:
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: ci-base
        deploymentconfig: ci-base
    spec:
      containers:
      - image: 172.30.0.128:5000/selenium-04/ci-base@sha256:230be100b492a043044c54613deb9bc7aa8a9a9058928733cb90b670ca5691fc
        imagePullPolicy: Always
        name: ci-base
        ports:
        - containerPort: 50000
          protocol: TCP
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /var/lib/jenkins
          name: ci-base-volume-1
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: ci-base-volume-1
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - ci-base
      from:
        kind: ImageStreamTag
        name: ci-base:latest
        namespace: selenium-04
    type: ImageChange
status: {}
